openapi: "3.0.3"

info:
  title: "Sample API"
  version: "1.0.0"

paths:
  "/api/v1/hello":
    get:
      summary: "hello"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "hello"
    
    post:
      summary: "create greeting"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "hide"
              required:
                - name
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "Hello hide!"

    delete:
      summary: "delete greeting"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "削除しました。"