openapi: "3.0.3"

info:
  title: "Sample API"
  version: "1.0.0"

paths:
  "/api/v1/hello":
    get:
      summary: "hello"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "hello"
    
    post:
      summary: "create greeting"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "hide"
              required:
                - name
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "Hello hide!"

    delete:
      summary: "delete greeting"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "削除しました。"

    put:
      summary: "update greeting"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "hide"
              required:
                - name
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "Hello John! こんにちは、hideさん!"
    
    patch:
      summary: "update greeting with additional message"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "How are you?"
              required:
                - message
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "Hello hide! How are you? こんにちは、hideさん!お元気ですか？"

  "/api/v1/hello/{id}":
    parameters:
      - name: id
        in: path
        description: "IDで絞り込んだパターン"
        required: true
        schema:
          type: integer
          minimum: 1
    get:
      summary: "Get greeting by ID"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: string
                example: "hello"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid ID"              